name: Main Workflow

on:
  push:
    branches: master

jobs:
  build-msbuild:
    name: Build msbuild
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        
      - name: Restore NuGet packages
        run: nuget restore framework.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Build The Solution
        run: msbuild framework.sln
