name: .NET Framework

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Initialize build on .NET Framework
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Navigate to Workspace
      run: cd ConsoleAp1
      
    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore ConsoleApp1.sln

    - name: Build Solution
      run: |
        msbuild.exe ConsoleApp1.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
        
    - name: Test
      run: dotnet test --no-restore --verbosity normal
