name: .NET Framework

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      


    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Build The Solution
      run: msbuild framework.sln
